### ISSUE TITLE
.json can't be imported to restore tabs

### ISSUE THREAD

**Issue by HenriFaust** [jensmeichler/clipboardjesus#199]
**Description**
Only .json text will be imported as a single note

**Steps to reproduce**
1. Import.json file via drag and drop

**Expected behaviour**
Tabs should be recreated

**Comment by jensmeichler** [comment]
This is actually how I implemented it intentionally 😅.
When you are dropping files that contain text (such as txt, json, etc), then the text of the file is created as a new note.
Files can be imported, when they have the boards.json extension (all the tabs) or the notes.json extension (a specific tab).
