### ISSUE TITLE
Only "www" subdomain points to app

### ISSUE THREAD

**Issue by similicious** [jensmeichler/clipboardjesus#2]
Try to access `https://clipboardjesus.com/` without the www subdomain. You'll see the strato "domain reserved" landing page.

I'm sure you can fix this ... "www"-subdomains are somwhat 90s style. :)

**Comment by daniel-landgraf** [comment]
**+1**

**Comment by jensmeichler** [comment]
Strato still bullies me.  I thought the solution would be an ALIAS / ANAME record to redirect to the www subdomain, but it's not available in the dns configuration..

![image](https://user-images.githubusercontent.com/50821093/173363254-78b816e8-506b-4329-8533-1e237b0ce315.png)

I think i must let the dns point to azure and fix it there...

**Comment by jensmeichler** [comment]
So.. I am leaving Strato and will transfer the domainhosting to hetzner.
Wish me luck :D

**Comment by jensmeichler** [comment]
The root domain redirects now to the www subdomain :D
