### ISSUE TITLE
note cards can be moved out of bounds by shrinking the window

### ISSUE THREAD

**Issue by Spaceplone** [jensmeichler/clipboardjesus#52]
## steps to reproduce

1. make app window big

2. move a note card to the bottom of the window.

3. shrink the app window vertically

## expected behavior

the note card is moved up with the bottom of the window

## actual behavior

the note card stays where it is and becomes inaccessible until the window is made large again
![Screenshot-5](https://user-images.githubusercontent.com/72419230/172423336-cc5ee7cd-91a3-48b7-9f16-22c71d357c6b.png)
![Screenshot-6](https://user-images.githubusercontent.com/72419230/172423342-078df733-43e1-4ca7-b811-5aa9e85601a7.png)

**Comment by jensmeichler** [comment]
Thank you for supporting 🎉

(In addition to your problem, I've seen that emojis don't seem to work on linux.)

Does scrolling work in your case?
This behavior is expected with notes, but you should be able to scroll horizontally and vertically.

You are right with dialogs. When you move a dialog out of the app window it is inaccessible until the windowsize is large enough to access the dialog. For example the edit dialog of a note.

I will try to fix the issue using dialogs. For notes i would expect the behaviour described above :D

**Comment by Spaceplone** [comment]
right. scrolling fixes the vertical out of bounds. still leaves the issue for moving out of bounds horizontally.  horizontal scrolling does not seem to be implemented


-----

on the topic of emoji on linux: they are a bit hit and miss. a fonts issue. they work fine in the browser, but not in the desktop app. the same behavior happens with discordapp and their desktop/web apps respectively. 

i installed the `fonts-noto-color-emoji` package and now i have working emoji everywhere

**Comment by jensmeichler** [comment]
For scrolling horizontally as well as vertically there should appear a scrollbar if anything is out of bounds. Is there an issue with the scrollbar (under Linux) as well, or is it just too dark? :DD
The vertical and horizontal mousewheel scroll should also work normally.
Maybe I should start developing on Linux hardware xD

**Comment by Spaceplone** [comment]
i get absolutely no horizontal scrollbar on linux. i tried clicking and dragging at the space at the bottom of the screen, but nothing reacts to that. 

i tried shift+scroll, because that should be the default way of scrolling horizontally, but that doesnt do anything

a workaround that works is to click and drag on empty space, making a selection rectangle and dragging that beyond the edges of the window.  that moves the visible area vertically and horizontally

**Comment by jensmeichler** [comment]
I will try to reproduce it on linux.
Regarding this issue i will also implement shift-scroll to scroll horizontally.

Update: The scrollbar is now just custom on windows.
    On Macos the scrollbehaviour is the same as in the browser.
    Linux i still have to test with desktop app v.0.1.2

**Comment by jensmeichler** [comment]
I was able to reproduce it using firefox. The latest release of the app should not have the issue. It should be able to scroll vertically using shift + scroll, using the touchpad and with the horizontally scrolling mousewheel :D
